apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-dags-folder
  labels:
    type: nfs
spec:
  storageClassName: dags
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/shared/airflow/dags"
    server: 192.168.20.3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder
  namespace: airflow-cluster
spec:
  storageClassName: dags
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
