# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: logs
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: Immediate
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-logs-pv
  labels:
    type: nfs
spec:
  storageClassName: logs
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/shared/airflow/logs"
    server: 192.168.20.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-logs-pvc
  namespace: airflow-cluster
spec:
  volumeName: airflow-local-logs-pv
  storageClassName: logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
