apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    type: nfs
spec:
  storageClassName: data-pv-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/shared/airflow/PV-data"
    server: 192.168.20.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: airflow-cluster
spec:
  storageClassName: data-pv-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
