apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: airflow-cluster
spec:
  storageClassName: data-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
